# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

RcppDiscEntropy <- function(vec, base = 2) {
    .Call(`_infosc_RcppDiscEntropy`, vec, base)
}

RcppDiscJoinEntropy <- function(mat, columns, base = 2) {
    .Call(`_infosc_RcppDiscJoinEntropy`, mat, columns, base)
}

RcppDiscMI <- function(mat, columns1, columns2, base = 10) {
    .Call(`_infosc_RcppDiscMI`, mat, columns1, columns2, base)
}

DiscCE <- function(mat, target_columns, conditional_columns, base = 10) {
    .Call(`_infosc_DiscCE`, mat, target_columns, conditional_columns, base)
}

